apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: pcjoshiatseashopapp 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pcjoshiatseashopapp 
    spec:
      containers:
        - name: pcjoshiatseashopapp 
          image: rlincregistry.azurecr.io/pcjoshiatseashopapp
          ports:
          - containerPort: 80